#服务器端口
server:
  port: 7770

#job服务配置
powerjob:
  worker:
    app-name: ${spring.application.name}
    port: 27777
    server-address: 127.0.0.1:7700

#数据源配置
spring:
  datasource:
    url: ${blade.datasource.dev.url}
    username: ${blade.datasource.dev.username}
    password: ${blade.datasource.dev.password}
