server:
  port: 4567

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
### 特殊情况下，查询结果返回List<Map>格式，会自动将查询结果为null的字段忽略，加入该配置
    call-setters-on-nulls: true

#spring:
#  jackson:
#    serialization:
#      FAIL_ON_EMPTY_BEANS: false
#mybatis-plus
#mybatis-plus:
#  #xml
#  mapper-locations: classpath:/mapper/*Mapper.xml
#  #bean
#  typeAliasesPackage: com.yyld.conair.ds.test.entity
#  global-config:
#    # 3:"UUID";
#    id-type: 3
#    field-strategy: 2
#    db-column-underline: true
#    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
#    logic-delete-value: 1
#    logic-not-delete-value: 0
##    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false
#    #JdbcTypeForNull
#    jdbc-type-for-null: 'null'
#
