-- -----------------------------------
-- 修改应用表的授权集合
-- -----------------------------------
UPDATE "BLADEX"."BLADE_CLIENT" SET AUTHORIZED_GRANT_TYPES = 'authorization_code,password,refresh_token,captcha,social,sms_code,register' where ID < 1123598811738675205;

-- -----------------------------------
-- 各表增加状态和是否已删除字段
-- -----------------------------------
ALTER TABLE "BLADEX"."BLADE_USER_APP"
    ADD ("STATUS" NUMBER(11) DEFAULT 1)
    ADD ("IS_DELETED" NUMBER(11) DEFAULT 0);
COMMENT ON COLUMN "BLADEX"."BLADE_USER_APP"."STATUS" IS '状态';
COMMENT ON COLUMN "BLADEX"."BLADE_USER_APP"."IS_DELETED" IS '是否已删除';

ALTER TABLE "BLADEX"."BLADE_USER_WEB"
    ADD ("STATUS" NUMBER(11) DEFAULT 1)
    ADD ("IS_DELETED" NUMBER(11) DEFAULT 0);
COMMENT ON COLUMN "BLADEX"."BLADE_USER_WEB"."STATUS" IS '状态';
COMMENT ON COLUMN "BLADEX"."BLADE_USER_WEB"."IS_DELETED" IS '是否已删除';

ALTER TABLE "BLADEX"."BLADE_USER_OTHER"
    ADD ("STATUS" NUMBER(11) DEFAULT 1)
    ADD ("IS_DELETED" NUMBER(11) DEFAULT 0);
COMMENT ON COLUMN "BLADEX"."BLADE_USER_OTHER"."STATUS" IS '状态';
COMMENT ON COLUMN "BLADEX"."BLADE_USER_OTHER"."IS_DELETED" IS '是否已删除';

ALTER TABLE "BLADEX"."BLADE_USER_DEPT"
    ADD ("STATUS" NUMBER(11) DEFAULT 1)
    ADD ("IS_DELETED" NUMBER(11) DEFAULT 0);
COMMENT ON COLUMN "BLADEX"."BLADE_USER_DEPT"."STATUS" IS '状态';
COMMENT ON COLUMN "BLADEX"."BLADE_USER_DEPT"."IS_DELETED" IS '是否已删除';

ALTER TABLE "BLADEX"."BLADE_USER_OAUTH"
    ADD ("STATUS" NUMBER(11) DEFAULT 1)
    ADD ("IS_DELETED" NUMBER(11) DEFAULT 0);
COMMENT ON COLUMN "BLADEX"."BLADE_USER_OAUTH"."STATUS" IS '状态';
COMMENT ON COLUMN "BLADEX"."BLADE_USER_OAUTH"."IS_DELETED" IS '是否已删除';

ALTER TABLE "BLADEX"."BLADE_ROLE"
    ADD ("STATUS" NUMBER(11) DEFAULT 1);
COMMENT ON COLUMN "BLADEX"."BLADE_ROLE"."STATUS" IS '状态';

ALTER TABLE "BLADEX"."BLADE_DEPT"
    ADD ("STATUS" NUMBER(11) DEFAULT 1);
COMMENT ON COLUMN "BLADEX"."BLADE_DEPT"."STATUS" IS '状态';

ALTER TABLE "BLADEX"."BLADE_DICT"
    ADD ("STATUS" NUMBER(11) DEFAULT 1);
COMMENT ON COLUMN "BLADEX"."BLADE_DICT"."STATUS" IS '状态';

ALTER TABLE "BLADEX"."BLADE_DICT_BIZ"
    ADD ("STATUS" NUMBER(11) DEFAULT 1);
COMMENT ON COLUMN "BLADEX"."BLADE_DICT_BIZ"."STATUS" IS '状态';
