#数据源配置
spring:
  data:
    redis:
      ##redis 单机环境配置
      host: 10.125.238.198
      port: 6379
      password: LcCw@redis#6379
      database: 0
      ssl:
        enabled: false
      ##redis 集群环境配置
      #cluster:
      #  nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003
      #  commandTimeout: 5000
  datasource:
    # MySql
    url: jdbc:mysql://localhost:3306/bladex_data?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: root

blade:
  ##大屏配置
  visual:
    #限流白名单
    white-list:
      - 127.0.0.1
      - 192.168.0.1
