package com.yyld.conair.ds.sap.entity;

import lombok.Data;

@Data
public class Itds {
    private String ID_;
    private String PARENT_ID_;
    private String TENANT_ID_;
    private String IP_;
    private String CREATE_BY_;
    private String CREATE_TIME_;
    private String UPDATE_BY_;
    private String UPDATE_TIME_;
    private String BUKRS;
    private String BUTXT;
    private String BELNR;
    private String GJAHR;
    private String BUZEI;
    private String BLART;
    private String BLDAT;
    private String BUDAT;
    private String MONAT;
    private String CPUDT;
    private String USNAM;
    private String TCODE;
    private String XBLNR;
    private String STBLG;
    private String BKTXT;
    private String XBLNR_ALT;
    private String SHKZG;
    private String MWSKZ;
    private String DMBTR;
    private String ZUONR;
    private String HKONT;
    private String TXT20;
    private String VBUND;
    private String NAME3;
    private String KUNNR;
    private String NAME1;
    private String LIFNR;
    private String NAME2;
    private String VBEL2;
    private String EBELN;
    private String EBELP;
    private String RSTGR;
    private String ANLN1;
    private String XREF1;
    private String XREF2;
    private String XREF3;
    private String XNEGP;
    private String ZYWFL;
    private String ZZTEST;
    private String ZZFIELD1;
    private String ZZFIELD2;
    private String ZZFIELD3;
    private String ZZFIELD4;
    private String ZZFIELD5;
    private String IT_FLAG;
    private String ASGN_FLAG;
    private String ZKMJQ;
    private String VRA_STATUS_;
    private String VRA_OBJ_ID;
    private String DIFF;
    private String TAX_DIFF;
    private String DMBTR_SH;
    private String TXT40;
    private String HANDLE_STAUS_01;
    private String HANDLE_STAUS_02;
    private String HANDLE_STAUS_03;
    private String ZYWM;
    private String HANDLE_STAUS_04;
    private String CURRENCY_;
    private String REPORT_CODE;
    private String REPORT_NAME;
    private String DATA_KEY_;
    private String CODE_NAME;
    private String CODE_DZ;
    private String CODE_DZ_NAME;
    private String REMARKS;
    private String STATUS_05;

}
